/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CharacterCard: typeof import('./src/components/Personagens/CharacterCard.vue')['default']
    DiceRoller: typeof import('./src/components/DiceRoller.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    IniciativeCard: typeof import('./src/components/IniciativeCard.vue')['default']
    ModalNewCharacter: typeof import('./src/components/Personagens/ModalNewCharacter.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
